---
title: "MLGroupware"
author: "John Hoegger"
date: "Saturday, December 20, 2014"
output: html_document
---

## Machine Learning Project 
### Johns Hopkins University (Coursera)

Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. 

My goal of this project is to use data from accelerometers on the belt, forearm, arm and dumbell of 6 participants to predict how well they were performing weight lifting.  

Six young health participants were asked to perform one set of 10 repetitions of barbell lifts correctly and incorrectly in 5 different ways. These were labeled as:
1. Exactly according to the specification   (Class A)
2. Throwing the elbows to the front         (Class B)
3. Lifting the dumbbell only halfway        (Class C)
4. Lowering the dumbbell only halfway       (Class D) 
5. Throwing the hips to the front           (Class E)

More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 


